[project]
name = "alterx"
dynamic = ["version"]
description = ""
authors = [
    {name = "Jet-Logic"},
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "alterx.__init__.__version__"}
